name: estoque-console-app
version: 0.1.0.0
github: 'githubuser/estoque-console-app'
license: BSD3
author: 'Author name here'
maintainer: 'example@example.com'
copyright: '2022 Author name here'

extra-source-files:
  - README.md
  - ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/githubuser/estoque-console-app#readme>

dependencies:
  - base >= 4.7 && < 5
  - cassava >= 0.5.2.0
  - bytestring >=0.10.12.0
  - vector >= 0.12.3.1
  - directory >= 1.3.6.0
  - text >= 1.2.4.1
  - deepseq (>=1.1)
  - time >= 1.9.2

library:
  source-dirs: src

executables:
  estoque-console-app-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - estoque-console-app

tests:
  estoque-console-app-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - estoque-console-app
